# shellcheck shell=bash
# Docker deployment engine: wraps the official frappe_docker project (pwd.yml)
# to run a containerized ERPNext stack behind the same erpnext-dev CLI as the
# native engine. Sourced by the toolkit entry point; do not execute directly.
#
# Design: we do NOT hand-roll a compose file. We clone frappe_docker at a pinned
# ref and use its upstream pwd.yml as the base, then overlay a small generated
# override (published port, pinned image tag, chosen site name + admin password)
# via a second -f file plus an --env-file. This keeps us aligned with upstream
# while honoring the operator's chosen site/port.

[[ -n "${_ERPNEXT_DEV_DOCKER_LOADED:-}" ]] && return 0
_ERPNEXT_DEV_DOCKER_LOADED=1

# ------------------------------------------------------------
# Paths / pins (overridable via environment)
# ------------------------------------------------------------
DOCKER_WORKDIR="${DOCKER_WORKDIR:-/opt/erpnext-dev/docker}"
FRAPPE_DOCKER_REPO="${FRAPPE_DOCKER_REPO:-https://github.com/frappe/frappe_docker.git}"
# Pin the frappe_docker checkout for reproducible provisioning. Set to an
# immutable commit SHA (e.g. FRAPPE_DOCKER_REF=<40-char-sha>) for a fully audited
# provision; the default tracks the upstream default branch. Either way the
# resolved commit SHA is recorded at provision time (see docker_write_pins).
FRAPPE_DOCKER_REF="${FRAPPE_DOCKER_REF:-main}"
# Pinned production-ready image published by the Frappe team. For maximum
# reproducibility pin by DIGEST rather than tag, e.g.
# DOCKER_ERPNEXT_IMAGE=frappe/erpnext@sha256:<digest>. The digest actually pulled
# is recorded at provision time (see docker_write_pins).
DOCKER_ERPNEXT_IMAGE="${DOCKER_ERPNEXT_IMAGE:-frappe/erpnext:v16.26.2}"
DOCKER_PROJECT_NAME="${DOCKER_PROJECT_NAME:-erpnext-dev}"
DOCKER_PUBLISH_PORT="${DOCKER_PUBLISH_PORT:-8080}"
DOCKER_READY_TIMEOUT="${DOCKER_READY_TIMEOUT:-900}"
# How long to wait for the one-shot create-site job (site + erpnext install) to
# complete before treating the install as failed.
DOCKER_CREATE_SITE_TIMEOUT="${DOCKER_CREATE_SITE_TIMEOUT:-900}"
DOCKER_CREDENTIALS_FILE="${DOCKER_CREDENTIALS_FILE:-${DOCKER_WORKDIR}/erpnext-dev-docker-credentials.txt}"
# Immutable-pin audit record: the exact frappe_docker commit SHA checked out and
# the resolved ERPNext image digest, captured at provision time.
DOCKER_PINS_FILE="${DOCKER_PINS_FILE:-${DOCKER_WORKDIR}/erpnext-dev.pins}"
DOCKER_FRAPPE_DOCKER_SHA="${DOCKER_FRAPPE_DOCKER_SHA:-}"
DOCKER_ERPNEXT_IMAGE_DIGEST="${DOCKER_ERPNEXT_IMAGE_DIGEST:-}"

# Disaster recovery (P3): every Docker backup is exported out of the sites volume
# to a durable, root-owned host artifact directory (db + files + site config +
# manifest + SHA256SUMS). Restore consumes those host artifacts, and a restore
# rehearsal proves the artifact restores into a clean site of the SAME image.
DOCKER_BACKUP_DIR="${DOCKER_BACKUP_DIR:-/var/backups/erpnext-dev/docker}"
DOCKER_RESTORE_REHEARSAL_FILE="${DOCKER_RESTORE_REHEARSAL_FILE:-/etc/erpnext-dev/docker-restore-rehearsal.env}"

# Off-site shipment (P6): durable host artifact -> off-VM (rsync/SSH, reusing the
# native OFF_VM_BACKUP_* config/keys) -> object storage (rclone, any S3/GCS/Azure/
# B2 remote). Object-storage settings live in their own root-owned config/state.
DOCKER_OBJECT_BACKUP_CONFIG_FILE="${DOCKER_OBJECT_BACKUP_CONFIG_FILE:-/etc/erpnext-dev/docker-object-backup.env}"
DOCKER_OBJECT_BACKUP_STATE_FILE="${DOCKER_OBJECT_BACKUP_STATE_FILE:-/etc/erpnext-dev/docker-object-backup.state}"

docker_clone_dir() { printf '%s/frappe_docker\n' "$DOCKER_WORKDIR"; }
docker_overrides_dir() { printf '%s/frappe_docker/overrides\n' "$DOCKER_WORKDIR"; }
docker_compose_base_file() { printf '%s/frappe_docker/pwd.yml\n' "$DOCKER_WORKDIR"; }
docker_override_file() { printf '%s/erpnext-dev.override.yml\n' "$DOCKER_WORKDIR"; }
docker_env_file() { printf '%s/erpnext-dev.env\n' "$DOCKER_WORKDIR"; }
# Production (compose.yaml) artifacts, generated by the toolkit and kept OUTSIDE
# the clone so `git reset --hard` on the checkout never wipes them.
docker_prod_base_file() { printf '%s/frappe_docker/compose.yaml\n' "$DOCKER_WORKDIR"; }
docker_prod_env_file() { printf '%s/erpnext-dev.prod.env\n' "$DOCKER_WORKDIR"; }
docker_prod_image_override_file() { printf '%s/erpnext-dev.prod.image.yml\n' "$DOCKER_WORKDIR"; }

# The Docker engine serves whatever site name is configured. Default to the
# toolkit SITE_NAME (e.g. erp.test) so local host mapping stays consistent.
docker_site_name() { printf '%s\n' "${DOCKER_SITE_NAME:-${SITE_NAME:-erp.test}}"; }

# ------------------------------------------------------------
# Deployment mode (development pwd.yml vs production compose.yaml)
# ------------------------------------------------------------
docker_mode() {
  case "$(printf '%s' "${DOCKER_MODE:-development}" | tr '[:upper:]' '[:lower:]' | tr -d '[:space:]')" in
    prod|production|public|public-vm) printf 'production\n' ;;
    *) printf 'development\n' ;;
  esac
}
docker_is_production() { [[ "$(docker_mode)" == "production" ]]; }
docker_mode_label() { docker_is_production && printf 'production\n' || printf 'development\n'; }

# Parse the image tag out of DOCKER_ERPNEXT_IMAGE for ERPNEXT_VERSION. When the
# image is pinned by digest (repo@sha256:...) there is no tag, so fall back to a
# harmless default (the generated image override sets the exact image anyway).
docker_image_tag() {
  local img="${DOCKER_ERPNEXT_IMAGE:-frappe/erpnext:latest}"
  case "$img" in
    *@sha256:*) printf 'latest\n' ;;
    *:*) printf '%s\n' "${img##*:}" ;;
    *) printf 'latest\n' ;;
  esac
}

# ------------------------------------------------------------
# Capability detection
# ------------------------------------------------------------
docker_binary_present() { command -v docker >/dev/null 2>&1; }

docker_daemon_ready() {
  docker_binary_present || return 1
  ${SUDO:-} docker info >/dev/null 2>&1
}

# Resolve the compose program into the caller-named array (default: DOCKER_COMPOSE_CMD).
# Prefers the modern "docker compose" plugin, falls back to the legacy
# "docker-compose" binary. Returns non-zero when neither is available.
#
# NOTE: we deliberately populate an array rather than echoing a "docker compose"
# string. The toolkit runs with IFS=$'\n\t' (no space), so an unquoted string
# containing a space would NOT word-split and bash would try to exec a single
# command literally named "docker compose".
docker_compose_resolve() {
  local __out_name="${1:-DOCKER_COMPOSE_CMD}"
  if docker compose version >/dev/null 2>&1; then
    eval "${__out_name}=(docker compose)"
  elif command -v docker-compose >/dev/null 2>&1; then
    eval "${__out_name}=(docker-compose)"
  else
    return 1
  fi
}

# Human-readable label for the detected compose program (used in preflight output).
docker_compose_program() {
  local -a __cmd=()
  local IFS=' '
  docker_compose_resolve __cmd || return 1
  printf '%s' "${__cmd[*]}"
}

docker_compose_available() {
  local -a __cmd=()
  docker_compose_resolve __cmd
}

host_arch_label() {
  case "$(uname -m 2>/dev/null || echo unknown)" in
    x86_64|amd64) printf 'amd64\n' ;;
    aarch64|arm64) printf 'arm64\n' ;;
    *) printf '%s\n' "$(uname -m 2>/dev/null || echo unknown)" ;;
  esac
}

# ------------------------------------------------------------
# Published-port conflict handling
# ------------------------------------------------------------
# True (returns 0) when nothing is listening on the given host TCP port.
# Uses ss, then netstat, then a bash /dev/tcp connect probe -- dependency-light
# and works before Docker itself has published anything.
docker_port_available() {
  local port="${1:-}"
  [[ "$port" =~ ^[0-9]+$ ]] || return 1
  if command -v ss >/dev/null 2>&1; then
    ! ${SUDO:-} ss -Hltn "sport = :${port}" 2>/dev/null | grep -q .
    return
  fi
  if command -v netstat >/dev/null 2>&1; then
    ! ${SUDO:-} netstat -ltn 2>/dev/null | awk '{print $4}' | grep -qE "[:.]${port}\$"
    return
  fi
  # Last resort: if a TCP connection opens, something is already listening.
  if (exec 3<>"/dev/tcp/127.0.0.1/${port}") 2>/dev/null; then
    exec 3>&- 2>/dev/null || true
    return 1
  fi
  return 0
}

# Ensure DOCKER_PUBLISH_PORT is free before we publish it. Interactive sessions
# are prompted for a replacement; non-interactive / -y runs auto-pick the next
# free port scanning upward. Sets DOCKER_PUBLISH_PORT to the resolved value.
docker_ensure_publish_port() {
  local port="${DOCKER_PUBLISH_PORT:-8080}" reply candidate tries=0
  if docker_port_available "$port"; then
    return 0
  fi
  warn "Host port ${port} is already in use by another process."
  if [[ -t 0 && "${ASSUME_YES:-0}" -ne 1 ]]; then
    while :; do
      read -r -p "Choose a different host port for ERPNext [1024-65535]: " reply
      if [[ ! "$reply" =~ ^[0-9]+$ ]] || (( reply < 1 || reply > 65535 )); then
        echo "Please enter a valid port number (1-65535)."
        continue
      fi
      if ! docker_port_available "$reply"; then
        echo "Port ${reply} is also in use; pick another."
        continue
      fi
      DOCKER_PUBLISH_PORT="$reply"
      ok "Using host port ${DOCKER_PUBLISH_PORT}."
      return 0
    done
  fi
  candidate="$port"
  while (( tries < 200 )); do
    candidate=$(( candidate + 1 ))
    (( candidate > 65535 )) && candidate=1024
    if docker_port_available "$candidate"; then
      DOCKER_PUBLISH_PORT="$candidate"
      warn "Auto-selected free host port ${DOCKER_PUBLISH_PORT} (was ${port})."
      return 0
    fi
    tries=$(( tries + 1 ))
  done
  fail "Could not find a free host port near ${port}. Set DOCKER_PUBLISH_PORT to an open port and retry."
}

# Read /etc/os-release and classify Docker-host support. Prints "STATUS|Pretty".
# Docker is OS-agnostic for the workload, so the officially supported Docker
# Engine hosts we track -- Ubuntu 24.04/26.04 and Debian 11/12/13 -- are OK;
# anything else is a soft WARN (still allowed) rather than a hard fail.
docker_host_os_eval() {
  local id="" ver="" pretty="unknown"
  if [[ -f /etc/os-release ]]; then
    # shellcheck disable=SC1091
    . /etc/os-release
    id="${ID:-}"
    ver="${VERSION_ID:-}"
    pretty="${PRETTY_NAME:-unknown}"
  fi
  case "${id}:${ver}" in
    ubuntu:24.04|ubuntu:26.04) printf 'OK|%s\n' "$pretty" ;;
    debian:11|debian:12|debian:13) printf 'OK|%s\n' "$pretty" ;;
    *) printf 'WARN|%s\n' "$pretty" ;;
  esac
}

# ------------------------------------------------------------
# Compose wrapper (mode-aware)
# ------------------------------------------------------------
# Ordered list of compose -f files for the active DOCKER_MODE, one per line.
#   development -> upstream pwd.yml + our generated override
#   production  -> upstream compose.yaml + mariadb + redis overrides + our
#                  generated image-pin override + the HTTP (noproxy) override.
#                  (P5 swaps the noproxy override for the Traefik https override.)
docker_compose_file_list() {
  local overrides
  overrides="$(docker_overrides_dir)"
  if docker_is_production; then
    printf '%s\n' "$(docker_prod_base_file)"
    printf '%s\n' "${overrides}/compose.mariadb.yaml"
    printf '%s\n' "${overrides}/compose.redis.yaml"
    printf '%s\n' "$(docker_prod_image_override_file)"
    printf '%s\n' "${overrides}/compose.noproxy.yaml"
  else
    printf '%s\n' "$(docker_compose_base_file)"
    printf '%s\n' "$(docker_override_file)"
  fi
}

docker_active_env_file() {
  if docker_is_production; then docker_prod_env_file; else docker_env_file; fi
}

# Run docker compose with the project name, the mode-appropriate file set, and
# the mode-appropriate env file. All extra args are passed straight through.
docker_compose() {
  local envf primary f
  local -a compose_cmd=() file_args=()
  docker_compose_resolve compose_cmd || { err "Docker Compose is not available."; return 1; }
  while IFS= read -r f; do
    [[ -n "$f" ]] || continue
    file_args+=(-f "$f")
  done < <(docker_compose_file_list)
  primary="${file_args[1]:-}"
  if [[ ! -f "$primary" ]]; then
    err "Compose base not found: ${primary}. Run the Docker install first ($(toolkit_cmd install))."
    return 1
  fi
  envf="$(docker_active_env_file)"
  # $SUDO is a single token ("sudo" or empty) so it is safe to leave unquoted;
  # the compose program is expanded from an array to survive the restricted IFS.
  # shellcheck disable=SC2086
  ${SUDO:-} "${compose_cmd[@]}" -p "$DOCKER_PROJECT_NAME" --env-file "$envf" "${file_args[@]}" "$@"
}

# ------------------------------------------------------------
# Host engine install (Docker Engine + compose plugin)
# ------------------------------------------------------------
# Install from Docker's official apt repository using a signed keyring and
# distribution-pinned packages. This is the hardened path: packages are
# GPG-verified by apt against Docker's published key, rather than executing an
# arbitrary remote script as root. Returns non-zero (so the caller can fall
# back) on any distro/repo problem -- e.g. a brand-new Debian codename whose
# packages Docker has not published yet. Only apt-based hosts (Ubuntu/Debian)
# are attempted here.
docker_install_engine_apt_repo() {
  require_sudo
  local id="" codename="" arch keyring list url
  if [[ -f /etc/os-release ]]; then
    # shellcheck disable=SC1091
    . /etc/os-release
    id="${ID:-}"
    codename="${VERSION_CODENAME:-}"
  fi
  case "$id" in
    ubuntu|debian) ;;
    *) return 1 ;;
  esac
  [[ -n "$codename" ]] || codename="$(lsb_release -cs 2>/dev/null || true)"
  [[ -n "$codename" ]] || return 1

  url="https://download.docker.com/linux/${id}"
  keyring="/etc/apt/keyrings/docker.gpg"
  list="/etc/apt/sources.list.d/docker.list"

  log "Installing Docker Engine from the official Docker apt repository (${id} ${codename})"

  export DEBIAN_FRONTEND=noninteractive
  $SUDO apt-get update -y >/dev/null 2>&1 || true
  $SUDO apt-get install -y ca-certificates curl gnupg >/dev/null 2>&1 || return 1

  $SUDO install -m 0755 -d /etc/apt/keyrings || return 1
  # Re-fetch the key each time so a rotated key is picked up; dearmor to a keyring.
  if ! curl -fsSL "${url}/gpg" | $SUDO gpg --batch --yes --dearmor -o "$keyring" 2>/dev/null; then
    return 1
  fi
  $SUDO chmod a+r "$keyring" || true

  arch="$(dpkg --print-architecture 2>/dev/null || echo amd64)"
  printf 'deb [arch=%s signed-by=%s] %s %s stable\n' "$arch" "$keyring" "$url" "$codename" \
    | $SUDO tee "$list" >/dev/null || return 1

  if ! $SUDO apt-get update -y >/dev/null 2>&1; then
    # Bad/empty repo for this codename: drop the source so a later apt-get on the
    # host is not left broken, then signal fallback.
    $SUDO rm -f "$list"
    return 1
  fi
  if ! $SUDO apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin >/dev/null 2>&1; then
    return 1
  fi
  return 0
}

# Legacy fallback: the official convenience script. Kept only for hosts where the
# apt repository path is unavailable (e.g. a Debian codename Docker has not yet
# published). We download first, then run, so the script is not piped straight
# from curl into a root shell.
docker_install_engine_convenience() {
  require_sudo
  warn "Falling back to the Docker convenience script (get.docker.com)."
  warn "This is less hardened than the signed apt repository; used only because the repository path was unavailable."
  local tmp
  tmp="$(mktemp /tmp/erpnext-dev-get-docker.XXXXXX.sh)" || return 1
  if ! curl -fsSL https://get.docker.com -o "$tmp"; then
    rm -f "$tmp"
    err "Could not download the Docker installation script. Check internet access and retry."
    return 1
  fi
  if ! $SUDO sh "$tmp"; then
    rm -f "$tmp"
    err "Docker Engine installation failed. Install Docker manually, then re-run."
    return 1
  fi
  rm -f "$tmp"
  return 0
}

docker_install_engine() {
  require_sudo

  if docker_daemon_ready && docker_compose_available; then
    ok "Docker Engine and Compose already present."
    return 0
  fi

  if docker_binary_present && ! docker_daemon_ready; then
    log "Docker is installed but the daemon is not reachable. Attempting to start it."
    $SUDO systemctl enable --now docker >/dev/null 2>&1 || true
    if docker_daemon_ready && docker_compose_available; then
      ok "Docker daemon started."
      return 0
    fi
  fi

  # Prefer the official signed apt repository; fall back to the convenience
  # script only if that path is unavailable for this host.
  if docker_install_engine_apt_repo; then
    ok "Docker Engine installed from the official Docker apt repository."
  else
    warn "Official Docker apt repository unavailable for this host."
    docker_install_engine_convenience || fail "Docker Engine installation failed. Install Docker manually, then re-run."
  fi

  $SUDO systemctl enable --now docker >/dev/null 2>&1 || true

  if docker_daemon_ready && docker_compose_available; then
    ok "Docker Engine and Compose installed."
    return 0
  fi
  fail "Docker was installed but the daemon or compose plugin is still unavailable."
}

# ------------------------------------------------------------
# Preflight (engine-aware summary block)
# ------------------------------------------------------------
docker_preflight() {
  local os_eval os_status os_pretty compat_status compat_detail

  os_eval="$(docker_host_os_eval)"
  os_status="${os_eval%%|*}"
  os_pretty="${os_eval#*|}"

  if docker_daemon_ready && docker_compose_available; then
    compat_status="OK"
    compat_detail="Docker daemon reachable, Compose available"
  elif docker_binary_present; then
    compat_status="WARN"
    compat_detail="Docker present; will start daemon / install Compose during setup"
  else
    compat_status="INFO"
    compat_detail="Docker not installed; will install during setup"
  fi

  local mode base_label
  mode="$(docker_mode_label)"
  if docker_is_production; then
    base_label="compose.yaml + mariadb/redis + HTTP (noproxy)"
  else
    base_label="pwd.yml (disposable dev stack)"
  fi

  ui_box_start "Docker Deployment Preflight"
  status_line "Operating system" "$os_status" "$os_pretty"
  status_line "Deployment engine" "INFO" "Docker"
  status_line "Deployment mode" "INFO" "$mode"
  status_line "Compose base" "INFO" "$base_label"
  status_line "Architecture" "INFO" "$(host_arch_label)"
  status_line "Docker compatibility" "$compat_status" "$compat_detail"
  status_line "ERPNext image" "INFO" "$DOCKER_ERPNEXT_IMAGE"
  status_line "Upstream pin" "INFO" "frappe_docker @ ${FRAPPE_DOCKER_REF}"
  status_line "Published port" "INFO" "${DOCKER_PUBLISH_PORT} -> 8080 (container)"
  status_line "Site name" "INFO" "$(docker_site_name)"
  ui_box_end

  if [[ "$os_status" == "WARN" ]]; then
    warn "Host OS is outside the tested set (Ubuntu 24.04/26.04, Debian 13). Docker install may still work."
  fi
  return 0
}

# ------------------------------------------------------------
# Provisioning
# ------------------------------------------------------------
docker_provision_workdir() {
  require_sudo
  local clone
  clone="$(docker_clone_dir)"

  $SUDO mkdir -p "$DOCKER_WORKDIR" || fail "Could not create ${DOCKER_WORKDIR}"

  if [[ -d "${clone}/.git" ]]; then
    log "Updating frappe_docker checkout (${FRAPPE_DOCKER_REF})"
    $SUDO git -C "$clone" fetch --depth 1 origin "$FRAPPE_DOCKER_REF" >/dev/null 2>&1 || true
    $SUDO git -C "$clone" checkout -q "$FRAPPE_DOCKER_REF" 2>/dev/null || true
    $SUDO git -C "$clone" reset --hard "origin/${FRAPPE_DOCKER_REF}" >/dev/null 2>&1 || true
  else
    log "Cloning frappe_docker (${FRAPPE_DOCKER_REF}) into ${clone}"
    $SUDO rm -rf "$clone"
    if ! $SUDO git clone --depth 1 --branch "$FRAPPE_DOCKER_REF" "$FRAPPE_DOCKER_REPO" "$clone" >/dev/null 2>&1; then
      # Fallback: full clone then checkout (branch may be a commit/tag).
      $SUDO rm -rf "$clone"
      $SUDO git clone "$FRAPPE_DOCKER_REPO" "$clone" >/dev/null 2>&1 || fail "Could not clone frappe_docker from ${FRAPPE_DOCKER_REPO}"
      $SUDO git -C "$clone" checkout -q "$FRAPPE_DOCKER_REF" 2>/dev/null || warn "Could not check out ref ${FRAPPE_DOCKER_REF}; using default branch."
    fi
  fi

  if [[ ! -f "$(docker_compose_base_file)" ]]; then
    fail "frappe_docker did not provide pwd.yml at $(docker_compose_base_file)."
  fi

  if docker_is_production; then
    local overrides missing=()
    overrides="$(docker_overrides_dir)"
    [[ -f "$(docker_prod_base_file)" ]] || missing+=("compose.yaml")
    [[ -f "${overrides}/compose.mariadb.yaml" ]] || missing+=("overrides/compose.mariadb.yaml")
    [[ -f "${overrides}/compose.redis.yaml" ]] || missing+=("overrides/compose.redis.yaml")
    [[ -f "${overrides}/compose.noproxy.yaml" ]] || missing+=("overrides/compose.noproxy.yaml")
    if [[ ${#missing[@]} -gt 0 ]]; then
      fail "frappe_docker checkout is missing production files: ${missing[*]}. Try a different FRAPPE_DOCKER_REF."
    fi
  fi

  # Record the exact commit actually checked out so the provision is auditable /
  # reproducible even when FRAPPE_DOCKER_REF is a moving branch like main.
  DOCKER_FRAPPE_DOCKER_SHA="$($SUDO git -C "$clone" rev-parse HEAD 2>/dev/null || echo unknown)"
  ok "frappe_docker ready at ${clone} (commit ${DOCKER_FRAPPE_DOCKER_SHA})"
}

# Best-effort: record the immutable RepoDigest of the pulled ERPNext image so the
# exact bits can be reproduced/audited later. No-op when docker or the image is
# not available yet.
docker_record_image_digest() {
  local digest
  docker_binary_present || return 0
  digest="$(${SUDO:-} docker inspect --format '{{if .RepoDigests}}{{index .RepoDigests 0}}{{end}}' "$DOCKER_ERPNEXT_IMAGE" 2>/dev/null || true)"
  [[ -n "$digest" ]] && DOCKER_ERPNEXT_IMAGE_DIGEST="$digest"
  return 0
}

# Persist immutable identifiers for the provisioned stack (audit / reproducibility).
# Written after images are pulled so the digest can be resolved.
docker_write_pins() {
  require_sudo
  docker_record_image_digest
  $SUDO mkdir -p "$DOCKER_WORKDIR"
  $SUDO tee "$DOCKER_PINS_FILE" >/dev/null <<EOF_DOCKER_PINS
# ERPNext Developer Toolkit - Docker immutable pins (audit / reproducibility)
# Generated $(date -u +%Y-%m-%dT%H:%M:%SZ)
# To reproduce this exact stack, set these in the environment before install:
#   FRAPPE_DOCKER_REF=<FRAPPE_DOCKER_SHA below>
#   DOCKER_ERPNEXT_IMAGE=<DOCKER_ERPNEXT_IMAGE_DIGEST below, if recorded>
FRAPPE_DOCKER_REPO=${FRAPPE_DOCKER_REPO}
FRAPPE_DOCKER_REF=${FRAPPE_DOCKER_REF}
FRAPPE_DOCKER_SHA=${DOCKER_FRAPPE_DOCKER_SHA:-unknown}
DOCKER_ERPNEXT_IMAGE=${DOCKER_ERPNEXT_IMAGE}
DOCKER_ERPNEXT_IMAGE_DIGEST=${DOCKER_ERPNEXT_IMAGE_DIGEST:-unrecorded}
EOF_DOCKER_PINS
  $SUDO chmod 644 "$DOCKER_PINS_FILE" 2>/dev/null || true
  ok "Recorded immutable pins to ${DOCKER_PINS_FILE}"
}

# Generate the env file consumed by compose interpolation. Admin/db passwords are
# kept here (root-owned, 600) instead of on the compose command line.
docker_write_env() {
  require_sudo
  local envf admin_pw db_pw
  envf="$(docker_env_file)"
  admin_pw="${DOCKER_ADMIN_PASSWORD:-$(random_password)}"
  db_pw="${DOCKER_DB_ROOT_PASSWORD:-admin}"
  DOCKER_ADMIN_PASSWORD="$admin_pw"

  $SUDO mkdir -p "$DOCKER_WORKDIR"
  $SUDO tee "$envf" >/dev/null <<EOF_DOCKER_ENV
DOCKER_ERPNEXT_IMAGE=${DOCKER_ERPNEXT_IMAGE}
DOCKER_PUBLISH_PORT=${DOCKER_PUBLISH_PORT}
DOCKER_SITE_NAME=$(docker_site_name)
DOCKER_ADMIN_PASSWORD=${admin_pw}
DOCKER_DB_ROOT_PASSWORD=${db_pw}
EOF_DOCKER_ENV
  $SUDO chown root:root "$envf" 2>/dev/null || true
  $SUDO chmod 600 "$envf" 2>/dev/null || true

  $SUDO tee "$DOCKER_CREDENTIALS_FILE" >/dev/null <<EOF_DOCKER_CREDS
# ERPNext Developer Toolkit - Docker engine credentials
# Site:      $(docker_site_name)
# Local URL: http://localhost:${DOCKER_PUBLISH_PORT}
# Friendly:  http://$(docker_site_name):${DOCKER_PUBLISH_PORT} (after host mapping)
Administrator password: ${admin_pw}
MariaDB root password:  ${db_pw}
EOF_DOCKER_CREDS
  $SUDO chown root:root "$DOCKER_CREDENTIALS_FILE" 2>/dev/null || true
  $SUDO chmod 600 "$DOCKER_CREDENTIALS_FILE" 2>/dev/null || true
}

# Overlay that pins the image, publishes the chosen port, forces the site header,
# and recreates the site with the configured name + admin password. Written with
# a quoted heredoc so ${...} stays literal for compose interpolation and $$ keeps
# its runtime-shell meaning inside the create-site command (as in upstream).
#
# NOTE: the create-site `until` condition is kept on a SINGLE physical line. In a
# YAML `>` folded scalar, backslash line-continuations become `\ ` (escaped space)
# once lines are folded, which turns the following `[[` from a bash keyword into a
# missing command ("[[: command not found") so the wait loop never completes and
# the site is never created. Do not reintroduce `\` continuations here.
docker_write_override() {
  require_sudo
  local override
  override="$(docker_override_file)"

  $SUDO mkdir -p "$DOCKER_WORKDIR"
  $SUDO tee "$override" >/dev/null <<'EOF_DOCKER_OVERRIDE'
services:
  backend:
    image: ${DOCKER_ERPNEXT_IMAGE}
  configurator:
    image: ${DOCKER_ERPNEXT_IMAGE}
  create-site:
    image: ${DOCKER_ERPNEXT_IMAGE}
    environment:
      SITE_NAME: ${DOCKER_SITE_NAME}
      ADMIN_PASSWORD: ${DOCKER_ADMIN_PASSWORD}
      DB_ROOT_PASSWORD: ${DOCKER_DB_ROOT_PASSWORD}
    entrypoint:
      - bash
      - -c
    command:
      - >
        wait-for-it -t 120 db:3306;
        wait-for-it -t 120 redis-cache:6379;
        wait-for-it -t 120 redis-queue:6379;
        export start=`date +%s`;
        until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host // empty"` ]] && [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty"` ]] && [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty"` ]];
        do
          echo "Waiting for sites/common_site_config.json to be created";
          sleep 5;
          if (( `date +%s`-start > 120 )); then
            echo "could not find sites/common_site_config.json with required keys";
            exit 1
          fi
        done;
        echo "sites/common_site_config.json found";
        if [ -d "sites/$$SITE_NAME" ]; then
          echo "Site $$SITE_NAME already exists; skipping create-site";
          exit 0;
        fi;
        bench new-site --mariadb-user-host-login-scope='%' --admin-password="$$ADMIN_PASSWORD" --db-root-username=root --db-root-password="$$DB_ROOT_PASSWORD" --install-app erpnext --set-default "$$SITE_NAME";
  db:
    image: mariadb:11.8
  frontend:
    image: ${DOCKER_ERPNEXT_IMAGE}
    environment:
      FRAPPE_SITE_NAME_HEADER: ${DOCKER_SITE_NAME}
    ports:
      - "${DOCKER_PUBLISH_PORT}:8080"
  queue-long:
    image: ${DOCKER_ERPNEXT_IMAGE}
  queue-short:
    image: ${DOCKER_ERPNEXT_IMAGE}
  scheduler:
    image: ${DOCKER_ERPNEXT_IMAGE}
  websocket:
    image: ${DOCKER_ERPNEXT_IMAGE}
EOF_DOCKER_OVERRIDE
  $SUDO chown root:root "$override" 2>/dev/null || true
  $SUDO chmod 644 "$override" 2>/dev/null || true
}

# ------------------------------------------------------------
# Lifecycle
# ------------------------------------------------------------
docker_compose_up() {
  require_sudo
  log "Starting the Docker stack (pulling images may take several minutes on first run)"
  docker_compose up -d
}

# Wait for the one-shot create-site job to finish and confirm it succeeded.
#
# `docker compose up -d` returns as soon as containers START, not when the
# one-shot create-site job COMPLETES. Without this check a failed site creation
# looks like a successful install and the published port then answers 404
# forever (the frontend is up but the backend has no such site). This blocks
# until create-site exits, surfaces its logs on failure, and returns non-zero so
# the caller can fail loudly with the real root cause.
docker_wait_for_site_creation() {
  require_sudo
  local deadline now cid state code
  deadline=$(( $(date +%s) + DOCKER_CREATE_SITE_TIMEOUT ))
  log "Waiting for the create-site job to finish (site: $(docker_site_name))"
  while :; do
    cid="$(docker_compose ps -aq create-site 2>/dev/null | tail -n1)"
    if [[ -n "$cid" ]]; then
      state="$(${SUDO:-} docker inspect -f '{{.State.Status}}' "$cid" 2>/dev/null || echo unknown)"
      if [[ "$state" == "exited" ]]; then
        code="$(${SUDO:-} docker inspect -f '{{.State.ExitCode}}' "$cid" 2>/dev/null || echo 1)"
        if [[ "$code" == "0" ]]; then
          ok "Site created: $(docker_site_name)"
          return 0
        fi
        err "create-site job failed (exit ${code}). Recent create-site logs:"
        docker_compose logs --no-color --tail 120 create-site 2>/dev/null || true
        return 1
      fi
    fi
    now="$(date +%s)"
    if [[ "$now" -ge "$deadline" ]]; then
      warn "create-site did not finish within ${DOCKER_CREATE_SITE_TIMEOUT}s. Recent create-site logs:"
      docker_compose logs --no-color --tail 120 create-site 2>/dev/null || true
      return 1
    fi
    sleep 5
  done
}

docker_runtime_start() {
  require_sudo
  if [[ ! -f "$(docker_compose_base_file)" ]]; then
    fail "Docker stack is not provisioned yet. Run: $(toolkit_cmd install)"
  fi
  docker_compose up -d && docker_ready && docker_print_access
}

docker_runtime_stop() {
  require_sudo
  docker_compose stop
}

docker_runtime_restart() {
  require_sudo
  docker_compose restart
}

docker_runtime_status() {
  require_sudo
  docker_compose ps
}

docker_runtime_logs() {
  require_sudo
  docker_compose logs --tail 160
}

# Poll the published HTTP endpoint until the site answers or timeout elapses.
docker_ready() {
  local url deadline now
  url="http://localhost:${DOCKER_PUBLISH_PORT}/api/method/ping"
  deadline=$(( $(date +%s) + DOCKER_READY_TIMEOUT ))
  log "Waiting for ERPNext to answer on http://localhost:${DOCKER_PUBLISH_PORT}"
  while :; do
    if curl -fsS -o /dev/null --max-time 5 "$url" 2>/dev/null; then
      ok "ERPNext is responding on port ${DOCKER_PUBLISH_PORT}"
      return 0
    fi
    now="$(date +%s)"
    if [[ "$now" -ge "$deadline" ]]; then
      warn "ERPNext did not respond within ${DOCKER_READY_TIMEOUT}s."
      echo "Check container logs with: $(toolkit_cmd logs)"
      return 1
    fi
    sleep 5
  done
}

# Run a bench command inside the backend container. Mirrors run_as_frappe for the
# native engine (this is the engine_bench seam).
docker_bench() {
  require_sudo
  docker_compose exec -T backend bench "$@"
}

# ------------------------------------------------------------
# Disaster recovery (P3): durable host artifacts + restore + rehearsal
# ------------------------------------------------------------
# Absolute bench dir inside the frappe/erpnext image (WORKDIR of every service).
docker_container_bench_dir() { printf '/home/frappe/frappe-bench\n'; }
# Per-site root for exported host artifacts: <DOCKER_BACKUP_DIR>/<site>/<prefix>/.
docker_backup_site_root() { printf '%s/%s\n' "$DOCKER_BACKUP_DIR" "$(docker_site_name)"; }

# Read a single KEY=value from a root-owned env file, permission-safe under sudo.
docker_env_value() {
  local envf="$1" key="$2"
  ${SUDO:-} awk -F= -v k="$key" '$1==k{v=$0; sub(/^[^=]*=/,"",v)} END{print v}' "$envf" 2>/dev/null || true
}

# Resolve the MariaDB root password used by restore/rehearsal. Production stores a
# generated password in the prod env file (DB_PASSWORD); development uses
# DOCKER_DB_ROOT_PASSWORD (default "admin").
docker_db_root_password() {
  local envf val
  envf="$(docker_active_env_file)"
  if docker_is_production; then
    val="$(docker_env_value "$envf" DB_PASSWORD)"
  else
    val="$(docker_env_value "$envf" DOCKER_DB_ROOT_PASSWORD)"
  fi
  printf '%s\n' "${val:-admin}"
}

# Newest exported host artifact directory for the current site (empty if none).
docker_latest_host_dir() {
  local root
  root="$(docker_backup_site_root)"
  ${SUDO:-} test -d "$root" || return 1
  ${SUDO:-} find "$root" -maxdepth 1 -mindepth 1 -type d -printf '%T@ %p\n' 2>/dev/null \
    | sort -nr | head -n1 | cut -d' ' -f2-
}

# Write MANIFEST.txt + SHA256SUMS into an exported artifact directory.
docker_backup_write_manifest() {
  local dir="$1" prefix="$2" site="$3"
  ${SUDO:-} tee "${dir}/MANIFEST.txt" >/dev/null <<EOF_DOCKER_BK_MANIFEST
# ERPNext Developer Toolkit - Docker backup manifest
site=${site}
prefix=${prefix}
created_at=$(date -u +%Y-%m-%dT%H:%M:%SZ)
engine=docker
mode=$(docker_mode_label)
image=${DOCKER_ERPNEXT_IMAGE}
image_digest=${DOCKER_ERPNEXT_IMAGE_DIGEST:-unrecorded}
frappe_docker_sha=${DOCKER_FRAPPE_DOCKER_SHA:-unrecorded}
compose_project=${DOCKER_PROJECT_NAME}
toolkit_version=${SCRIPT_VERSION:-unknown}
EOF_DOCKER_BK_MANIFEST
  # Checksums over every component (excluding SHA256SUMS itself) for verify/restore.
  ${SUDO:-} sh -c "cd '$dir' && find . -maxdepth 1 -type f ! -name SHA256SUMS -printf '%P\n' | sort | xargs -r sha256sum > SHA256SUMS" 2>/dev/null || true
  ${SUDO:-} chmod -R go-rwx "$dir" 2>/dev/null || true
}

# Take a backup inside the backend container, then EXPORT the newest set out of
# the sites volume to a durable, root-owned host artifact directory. This is the
# heart of P3: a Docker volume alone is not a backup, so every backup lands as a
# self-describing host artifact that verify/restore/rehearsal can consume.
docker_backup() {
  require_sudo
  local include_files="${1:-false}"
  local site bench db_rel db_base prefix host_dir f copied=0

  site="$(docker_site_name)"
  bench="$(docker_container_bench_dir)"

  if [[ "$include_files" == "true" ]]; then
    log "Creating database + files backup for ${site} (Docker)"
    docker_bench --site "$site" backup --with-files || { err "bench backup failed."; return 1; }
  else
    log "Creating database backup for ${site} (Docker)"
    docker_bench --site "$site" backup || { err "bench backup failed."; return 1; }
  fi

  # Identify the newest database file inside the container (relative to bench dir).
  db_rel="$(docker_compose exec -T backend bash -c "ls -1t sites/${site}/private/backups/*-database.sql.gz 2>/dev/null | head -n1" 2>/dev/null | tr -d '\r')"
  if [[ -z "$db_rel" ]]; then
    err "Could not locate the new database backup inside the container."
    return 1
  fi
  db_base="$(basename "$db_rel")"
  prefix="${db_base%-database.sql.gz}"

  host_dir="$(docker_backup_site_root)/${prefix}"
  $SUDO mkdir -p "$host_dir" || { err "Could not create host artifact dir ${host_dir}"; return 1; }
  log "Exporting backup set ${prefix} to ${host_dir}"

  for f in "${prefix}-database.sql.gz" \
           "${prefix}-site_config_backup.json" \
           "${prefix}-files.tar" "${prefix}-files.tar.gz" \
           "${prefix}-private-files.tar" "${prefix}-private-files.tar.gz"; do
    if docker_compose exec -T backend test -f "sites/${site}/private/backups/${f}" >/dev/null 2>&1; then
      if docker_compose cp "backend:${bench}/sites/${site}/private/backups/${f}" "${host_dir}/${f}" >/dev/null 2>&1; then
        copied=$((copied+1))
      else
        warn "Could not copy ${f} out of the container."
      fi
    fi
  done

  if [[ "$copied" -eq 0 ]]; then
    err "No backup files were exported to the host."
    return 1
  fi

  docker_backup_write_manifest "$host_dir" "$prefix" "$site"
  ok "Durable host backup exported: ${host_dir}"
  echo "Verify with:  $(toolkit_cmd backup-verify)"
  echo "Restore with: $(toolkit_cmd restore-full)"
  return 0
}

docker_list_backups() {
  require_sudo
  local site root
  site="$(docker_site_name)"
  root="$(docker_backup_site_root)"

  echo
  echo "============================================================"
  echo "ERPNext Backups (Docker)"
  echo "============================================================"
  echo "Site: ${site}"
  echo "Host artifact folder: ${root}"
  echo
  echo "Durable host backup sets (newest first):"
  if $SUDO test -d "$root"; then
    $SUDO find "$root" -maxdepth 1 -mindepth 1 -type d -printf '%T@ %p\n' 2>/dev/null \
      | sort -nr | head -20 \
      | while read -r _ts dir; do
          printf '  %s  (%s)\n' "$(basename "$dir")" "$($SUDO du -sh "$dir" 2>/dev/null | awk '{print $1}')"
        done
  else
    echo "  none — create one with: $(toolkit_cmd backup)"
  fi
  echo
  echo "In-container backups (sites volume, not durable on their own):"
  docker_bench --site "$site" list-backups 2>/dev/null | sed 's/^/  /' || echo "  (stack not running)"
  echo
  echo "Tip: restore consumes a host backup set folder from above."
  echo "============================================================"
}

# Readability test for an exported tar/tar.gz component.
docker_backup_tar_ok() {
  local file="$1"
  if [[ "$file" == *.gz ]]; then
    $SUDO tar -tzf "$file" >/dev/null 2>&1
  else
    $SUDO tar -tf "$file" >/dev/null 2>&1
  fi
}

# Verify an exported host artifact (default: newest). Checks gzip/tar/json
# integrity and, when present, the SHA256SUMS manifest. No restore is performed.
docker_backup_verify() {
  require_sudo
  local dir="${1:-}" prefix fail_count=0 f
  [[ -n "$dir" ]] || dir="$(docker_latest_host_dir || true)"

  ui_box_start "Backup Verification (Docker)"
  status_line "Mode" "INFO" "checks exported host artifact; no restore is performed"
  status_line "Site" "INFO" "$(docker_site_name)"

  if [[ -z "$dir" ]] || ! $SUDO test -d "$dir"; then
    status_line "Host backup" "FAIL" "no durable host backup found; run $(toolkit_cmd backup)"
    ui_box_end
    return 1
  fi
  prefix="$(basename "$dir")"
  status_line "Artifact" "INFO" "$dir"
  status_line "Backup set" "INFO" "$prefix"

  if $SUDO test -f "${dir}/${prefix}-database.sql.gz" && $SUDO gzip -t "${dir}/${prefix}-database.sql.gz" >/dev/null 2>&1; then
    status_line "Database" "OK" "gzip readable ($($SUDO du -h "${dir}/${prefix}-database.sql.gz" 2>/dev/null | awk '{print $1}'))"
  else
    status_line "Database" "FAIL" "missing or unreadable"
    fail_count=$((fail_count+1))
  fi

  for f in "${prefix}-files.tar" "${prefix}-files.tar.gz"; do
    if $SUDO test -f "${dir}/${f}"; then
      if docker_backup_tar_ok "${dir}/${f}"; then
        status_line "Public files" "OK" "$f readable"
      else
        status_line "Public files" "FAIL" "$f unreadable"
        fail_count=$((fail_count+1))
      fi
      break
    fi
  done
  for f in "${prefix}-private-files.tar" "${prefix}-private-files.tar.gz"; do
    if $SUDO test -f "${dir}/${f}"; then
      if docker_backup_tar_ok "${dir}/${f}"; then
        status_line "Private files" "OK" "$f readable"
      else
        status_line "Private files" "FAIL" "$f unreadable"
        fail_count=$((fail_count+1))
      fi
      break
    fi
  done

  if $SUDO test -f "${dir}/${prefix}-site_config_backup.json"; then
    status_line "Site config" "OK" "present"
  else
    status_line "Site config" "WARN" "not exported"
  fi

  if $SUDO test -f "${dir}/SHA256SUMS"; then
    if $SUDO sh -c "cd '$dir' && sha256sum -c SHA256SUMS >/dev/null 2>&1"; then
      status_line "Checksums" "OK" "SHA256SUMS verified"
    else
      status_line "Checksums" "FAIL" "SHA256SUMS mismatch"
      fail_count=$((fail_count+1))
    fi
  else
    status_line "Checksums" "WARN" "no SHA256SUMS in artifact"
  fi

  if [[ "$fail_count" -eq 0 ]]; then
    status_line "Verification" "OK" "artifact is readable and consistent"
  else
    status_line "Verification" "FAIL" "${fail_count} problem(s); do not rely on this backup"
  fi
  echo
  echo "This is not a restore test. Prove restore end-to-end with: $(toolkit_cmd docker-restore-rehearsal)"
  ui_box_end
  [[ "$fail_count" -eq 0 ]]
}

# Interactively pick a host artifact directory (default: newest). Non-interactive
# / -y runs always use the newest set.
docker_pick_host_dir() {
  local latest reply root
  latest="$(docker_latest_host_dir || true)"
  root="$(docker_backup_site_root)"
  if [[ -z "$latest" ]]; then
    return 1
  fi
  if [[ ! -t 0 || "${ASSUME_YES:-0}" -eq 1 ]]; then
    printf '%s\n' "$latest"
    return 0
  fi
  read -r -p "Backup set to restore [$(basename "$latest")]: " reply >&2
  if [[ -z "$reply" ]]; then
    printf '%s\n' "$latest"
  elif [[ "$reply" = /* ]]; then
    printf '%s\n' "$reply"
  else
    printf '%s/%s\n' "$root" "$reply"
  fi
}

# Restore the current site from an exported host artifact. kind: db|full.
# Copies the artifact back into the container backups dir, then runs bench
# restore. Takes an emergency backup first (destructive operation).
docker_restore() {
  require_sudo
  local kind="${1:-full}" site bench dir prefix pw
  local db_base f
  site="$(docker_site_name)"
  bench="$(docker_container_bench_dir)"

  docker_list_backups
  echo
  dir="$(docker_pick_host_dir || true)"
  if [[ -z "$dir" ]] || ! $SUDO test -d "$dir"; then
    err "No host backup set selected. Create one with: $(toolkit_cmd backup)"
    return 1
  fi
  prefix="$(basename "$dir")"

  if ! $SUDO test -f "${dir}/${prefix}-database.sql.gz"; then
    err "Selected set has no database file: ${dir}/${prefix}-database.sql.gz"
    return 1
  fi

  echo
  warn "Restore OVERWRITES the running ${site} database (Docker engine, ${prefix})."
  if [[ -t 0 && "${ASSUME_YES:-0}" -ne 1 ]]; then
    local answer
    read -r -p "Type the site name (${site}) to confirm restore: " answer
    [[ "$answer" == "$site" ]] || { err "Confirmation did not match. Restore cancelled."; return 1; }
  fi

  pw="$(docker_db_root_password)"
  db_base="${prefix}-database.sql.gz"

  log "Creating emergency backup before restore"
  docker_backup true || warn "Emergency backup failed; continuing only because restore was explicitly confirmed."

  # Copy the chosen artifact into the container backups dir so bench can read it.
  docker_compose cp "${dir}/${db_base}" "backend:${bench}/sites/${site}/private/backups/${db_base}" >/dev/null 2>&1 \
    || { err "Could not copy the database backup into the container."; return 1; }

  local -a restore_args=(--site "$site" --force restore "sites/${site}/private/backups/${db_base}"
                         --db-root-username root --db-root-password "$pw")

  if [[ "$kind" == "full" ]]; then
    for f in "${prefix}-files.tar" "${prefix}-files.tar.gz"; do
      if $SUDO test -f "${dir}/${f}"; then
        docker_compose cp "${dir}/${f}" "backend:${bench}/sites/${site}/private/backups/${f}" >/dev/null 2>&1 \
          && restore_args+=(--with-public-files "sites/${site}/private/backups/${f}")
        break
      fi
    done
    for f in "${prefix}-private-files.tar" "${prefix}-private-files.tar.gz"; do
      if $SUDO test -f "${dir}/${f}"; then
        docker_compose cp "${dir}/${f}" "backend:${bench}/sites/${site}/private/backups/${f}" >/dev/null 2>&1 \
          && restore_args+=(--with-private-files "sites/${site}/private/backups/${f}")
        break
      fi
    done
  fi

  log "Restoring ${kind} backup ${prefix} into ${site}"
  if ! docker_compose exec -T backend bench "${restore_args[@]}"; then
    err "bench restore failed. Inspect with: $(toolkit_cmd logs)"
    return 1
  fi

  log "Running post-restore migrate"
  docker_bench --site "$site" migrate || warn "migrate reported an issue; review the logs."
  docker_bench --site "$site" clear-cache >/dev/null 2>&1 || true
  docker_runtime_restart || true

  ok "Restore completed for ${site} from set ${prefix}."
  docker_verify_access
  return 0
}

# Sanitize a value for the flat evidence record.
docker_rehearsal_sanitize() {
  printf '%s' "${1:-}" | tr '\n\t' '  ' | sed -E 's/[^A-Za-z0-9._:@/+=, -]/-/g' | cut -c1-240
}

# Automated Docker restore rehearsal (the containerized analog of the native
# disposable-VM rehearsal). Proves the exported artifact actually restores into a
# CLEAN, throwaway site running on the SAME image, WITHOUT touching the live site,
# then records dated evidence. Safe to run on the production stack because the
# rehearsal uses a temporary site that is dropped afterward.
docker_restore_rehearsal() {
  require_sudo
  local site bench dir prefix pw temp_site db_base rc=0 apps="" recorded_at result

  site="$(docker_site_name)"
  bench="$(docker_container_bench_dir)"

  ui_box_start "Docker Restore Rehearsal"
  status_line "Site" "INFO" "$site"
  status_line "Mode" "INFO" "$(docker_mode_label)"
  echo "Restores an exported backup into a throwaway site on the same image, then drops it."
  echo

  if ! docker_wait_service_running backend 60; then
    status_line "Stack" "FAIL" "backend container is not running; start it first ($(toolkit_cmd start))"
    ui_box_end
    return 1
  fi

  # Use the newest verified artifact; take a fresh one when none exists yet.
  dir="$(docker_latest_host_dir || true)"
  if [[ -z "$dir" ]]; then
    log "No host backup yet; taking one for the rehearsal"
    docker_backup false || { status_line "Backup" "FAIL" "could not create a backup to rehearse"; ui_box_end; return 1; }
    dir="$(docker_latest_host_dir || true)"
  fi
  if [[ -z "$dir" ]] || ! $SUDO test -d "$dir"; then
    status_line "Backup" "FAIL" "no host backup available"
    ui_box_end
    return 1
  fi
  prefix="$(basename "$dir")"
  status_line "Backup set" "OK" "$prefix"

  if ! docker_backup_verify "$dir" >/dev/null 2>&1; then
    status_line "Artifact integrity" "FAIL" "verification failed; aborting rehearsal"
    ui_box_end
    return 1
  fi
  status_line "Artifact integrity" "OK" "database/tar/checksums verified"

  pw="$(docker_db_root_password)"
  db_base="${prefix}-database.sql.gz"
  temp_site="rehearsal-$(date +%s).localhost"
  status_line "Rehearsal site" "INFO" "$temp_site (temporary)"

  # Copy the artifact DB into the container so bench can read it.
  if ! docker_compose cp "${dir}/${db_base}" "backend:${bench}/sites/${site}/private/backups/${db_base}" >/dev/null 2>&1; then
    status_line "Prepare" "FAIL" "could not stage the backup into the container"
    ui_box_end
    return 1
  fi

  log "Creating throwaway site ${temp_site}"
  if ! docker_compose exec -T backend bench new-site \
      --mariadb-user-host-login-scope='%' \
      --admin-password "rehearsal-$(date +%s)" \
      --db-root-username root \
      --db-root-password "$pw" \
      --no-mariadb-socket \
      "$temp_site" >/dev/null 2>&1; then
    # Retry without --no-mariadb-socket for older bench versions.
    docker_compose exec -T backend bench new-site \
      --mariadb-user-host-login-scope='%' \
      --admin-password "rehearsal-$(date +%s)" \
      --db-root-username root \
      --db-root-password "$pw" \
      "$temp_site" >/dev/null 2>&1 || rc=1
  fi

  if [[ "$rc" -eq 0 ]]; then
    log "Restoring ${prefix} into ${temp_site}"
    if docker_compose exec -T backend bench --site "$temp_site" --force restore \
        "sites/${site}/private/backups/${db_base}" \
        --db-root-username root --db-root-password "$pw" >/dev/null 2>&1; then
      apps="$(docker_compose exec -T backend bench --site "$temp_site" list-apps 2>/dev/null | tr -d '\r' | tr '\n' ' ' | sed -E 's/ +/ /g; s/^ +| +$//g')"
      if printf '%s' "$apps" | grep -qi 'erpnext'; then
        status_line "Restore into clean site" "OK" "erpnext present after restore"
      else
        status_line "Restore into clean site" "WARN" "restored, but erpnext not detected (apps: ${apps:-none})"
        rc=1
      fi
    else
      status_line "Restore into clean site" "FAIL" "bench restore failed on the rehearsal site"
      rc=1
    fi
  else
    status_line "Rehearsal site" "FAIL" "could not create the throwaway site"
  fi

  # Always try to drop the throwaway site so no residue is left behind.
  log "Dropping throwaway site ${temp_site}"
  if docker_compose exec -T backend bench drop-site "$temp_site" \
      --db-root-username root --db-root-password "$pw" --force --no-backup >/dev/null 2>&1; then
    status_line "Cleanup" "OK" "throwaway site dropped"
  else
    status_line "Cleanup" "WARN" "could not drop ${temp_site}; drop it manually"
  fi

  recorded_at="$(date -Is 2>/dev/null || date)"
  if [[ "$rc" -eq 0 ]]; then
    result="full_restore_into_clean_site_completed"
    status_line "Rehearsal" "OK" "backup restores into a clean site of the same image"
  else
    result="restore_rehearsal_failed"
    status_line "Rehearsal" "FAIL" "see messages above"
  fi

  $SUDO mkdir -p "$(dirname "$DOCKER_RESTORE_REHEARSAL_FILE")"
  $SUDO tee "$DOCKER_RESTORE_REHEARSAL_FILE" >/dev/null <<EOF_DOCKER_REHEARSAL
DOCKER_RESTORE_REHEARSAL_STATUS=$([[ "$rc" -eq 0 ]] && echo OK || echo FAIL)
DOCKER_RESTORE_REHEARSAL_RECORDED_AT=${recorded_at}
DOCKER_RESTORE_REHEARSAL_SITE=${site}
DOCKER_RESTORE_REHEARSAL_MODE=$(docker_mode_label)
DOCKER_RESTORE_REHEARSAL_BACKUP_SET=${prefix}
DOCKER_RESTORE_REHEARSAL_TEMP_SITE=${temp_site}
DOCKER_RESTORE_REHEARSAL_IMAGE=${DOCKER_ERPNEXT_IMAGE}
DOCKER_RESTORE_REHEARSAL_IMAGE_DIGEST=${DOCKER_ERPNEXT_IMAGE_DIGEST:-unrecorded}
DOCKER_RESTORE_REHEARSAL_APPS=$(docker_rehearsal_sanitize "$apps")
DOCKER_RESTORE_REHEARSAL_RESULT=${result}
DOCKER_RESTORE_REHEARSAL_TOOLKIT_VERSION=${SCRIPT_VERSION:-unknown}
EOF_DOCKER_REHEARSAL
  $SUDO chown root:root "$DOCKER_RESTORE_REHEARSAL_FILE" 2>/dev/null || true
  $SUDO chmod 600 "$DOCKER_RESTORE_REHEARSAL_FILE" 2>/dev/null || true
  status_line "Evidence" "INFO" "$DOCKER_RESTORE_REHEARSAL_FILE"
  ui_next "$(toolkit_cmd docker-restore-evidence)" "$(toolkit_cmd backup-status)"
  ui_box_end
  [[ "$rc" -eq 0 ]]
}

# Show the recorded Docker restore-rehearsal evidence.
docker_show_restore_evidence() {
  require_sudo
  ui_box_start "Docker Restore Rehearsal Evidence"
  status_line "Site" "INFO" "$(docker_site_name)"
  status_line "Record file" "$($SUDO test -f "$DOCKER_RESTORE_REHEARSAL_FILE" && echo OK || echo WARN)" "$DOCKER_RESTORE_REHEARSAL_FILE"
  if $SUDO test -f "$DOCKER_RESTORE_REHEARSAL_FILE"; then
    local status
    status="$(docker_env_value "$DOCKER_RESTORE_REHEARSAL_FILE" DOCKER_RESTORE_REHEARSAL_STATUS)"
    status_line "Last rehearsal" "$([[ "$status" == OK ]] && echo OK || echo WARN)" "${status:-unknown}"
    echo
    echo "Recorded metadata:"
    $SUDO sed -E 's/(PASSWORD|SECRET|TOKEN|KEY)=.*/=[REDACTED]/' "$DOCKER_RESTORE_REHEARSAL_FILE" | sed 's/^/  /'
  else
    echo
    echo "No Docker restore rehearsal recorded yet. Run:"
    echo "  $(toolkit_cmd docker-restore-rehearsal)"
  fi
  ui_box_end
}

# ------------------------------------------------------------
# Off-site shipment (P6): host artifact -> off-VM (rsync) -> object storage
# ------------------------------------------------------------
# The source shipped off-VM is the per-site durable host artifact tree from P3
# (DOCKER_BACKUP_DIR/<site>/<set>/...). Each set carries its own SHA256SUMS, so
# shipment can be verified at the destination rather than trusted blindly.
docker_offvm_source_dir() { docker_backup_site_root; }

# Build the ssh command array used for remote verification (mirrors the options
# in the native off_vm_backup_ssh_command_string, but as an array we can exec).
docker_offvm_ssh_cmd() {
  local __out="${1:-DOCKER_OFFVM_SSH_CMD}"
  local identity="${OFF_VM_BACKUP_SSH_IDENTITY:-}"
  if [[ -n "$identity" ]]; then
    eval "${__out}=(ssh -o BatchMode=yes -o ConnectTimeout=15 -o StrictHostKeyChecking=accept-new -i \"\$identity\")"
  else
    eval "${__out}=(ssh -o BatchMode=yes -o ConnectTimeout=15 -o StrictHostKeyChecking=accept-new)"
  fi
}

# Verify SHA256SUMS of every shipped set at the rsync destination. Best-effort:
# a picky remote shell should not fail the whole run (local sets are already
# checksummed), so callers treat a non-zero return as a soft WARN.
docker_offvm_remote_verify() {
  local target="$1" host remote_path
  local -a ssh_cmd=()
  host="${target%%:*}"
  remote_path="${target#*:}"
  [[ -n "$host" && -n "$remote_path" && "$host" != "$target" ]] || return 1
  docker_offvm_ssh_cmd ssh_cmd
  ${SUDO:-} "${ssh_cmd[@]}" "$host" \
    "cd '${remote_path}' 2>/dev/null || exit 3; rc=0; for d in */; do [ -f \"\${d}SHA256SUMS\" ] || continue; ( cd \"\$d\" && sha256sum -c SHA256SUMS >/dev/null 2>&1 ) || rc=1; done; exit \$rc" \
    >/dev/null 2>&1
}

# Off-VM rsync of the durable host artifacts for the Docker engine. Reuses the
# native OFF_VM_BACKUP_* configuration (configure-rsync-backup-target, keys,
# backup-server-setup, delete mode, state file). mode: dry-run|run.
docker_offvm_rsync() {
  require_sudo
  local mode="${1:-run}" src target ssh_cmd_str
  local -a rsync_cmd=()

  off_vm_backup_load_config
  validate_off_vm_backup_target "${OFF_VM_BACKUP_TARGET:-}" \
    || fail "Off-VM target not configured/invalid. Run: $(toolkit_cmd configure-rsync-backup-target)"
  target="$OFF_VM_BACKUP_TARGET"
  src="$(docker_offvm_source_dir)"
  $SUDO test -d "$src" || fail "No durable host backups at ${src}. Run $(toolkit_cmd backup) first."
  off_vm_backup_ensure_rsync

  ssh_cmd_str="$(off_vm_backup_ssh_command_string)"
  rsync_cmd=(rsync -az --human-readable --info=stats2 -e "$ssh_cmd_str")
  [[ "$mode" == "dry-run" ]] && rsync_cmd+=(--dry-run)
  [[ "${OFF_VM_BACKUP_RSYNC_DELETE:-false}" == "true" ]] && rsync_cmd+=(--delete)
  rsync_cmd+=("${src}/" "$target")

  ui_box_start "$([[ "$mode" == "dry-run" ]] && echo "Docker Off-VM Backup Dry Run" || echo "Docker Off-VM Backup")"
  status_line "Engine" "INFO" "Docker ($(docker_mode_label))"
  status_line "Site" "INFO" "$(docker_site_name)"
  status_line "Source" "INFO" "${src}/ (durable host artifacts)"
  status_line "Target" "INFO" "$target"
  status_line "Delete mode" "INFO" "${OFF_VM_BACKUP_RSYNC_DELETE:-false}"
  echo
  if [[ "$mode" == "dry-run" ]]; then
    echo "Running rsync dry run. No files are copied or deleted."
  else
    echo "Ships durable host backup artifacts off this VM. Local backups are not removed."
    if [[ -t 0 && "${ASSUME_YES:-0}" -ne 1 ]]; then
      if ! confirm "Run off-VM rsync backup now?"; then
        warn "Off-VM backup cancelled."
        ui_box_end
        return 0
      fi
    fi
  fi

  echo
  log "Starting rsync ${mode}"
  # Artifacts are root-owned (0700), so rsync must run as root to read them.
  if ${SUDO:-} "${rsync_cmd[@]}"; then
    if [[ "$mode" == "dry-run" ]]; then
      status_line "Dry run" "OK" "rsync dry run completed"
    elif docker_offvm_remote_verify "$target"; then
      status_line "Remote verify" "OK" "SHA256SUMS verified at destination"
      off_vm_backup_write_state "OK" "rsync completed; remote checksums verified"
      status_line "Off-VM backup" "OK" "shipped and verified"
    else
      status_line "Remote verify" "WARN" "could not verify remote checksums (shipment completed)"
      off_vm_backup_write_state "OK" "rsync completed; remote verify unavailable"
      status_line "Off-VM backup" "OK" "shipped (verify destination manually)"
    fi
  else
    [[ "$mode" != "dry-run" ]] && off_vm_backup_write_state "FAIL" "rsync failed"
    status_line "Off-VM backup" "FAIL" "rsync command failed"
  fi
  ui_next "$(toolkit_cmd off-vm-backup-status)" "$(toolkit_cmd docker-object-backup)"
  ui_box_end
}

# Off-VM plan/status for the Docker engine (parity with the native screens, but
# reporting the durable host-artifact source instead of a bench backup folder).
docker_offvm_plan() {
  require_sudo
  off_vm_backup_load_config
  ui_box_start "Docker Off-VM Backup Plan"
  status_line "Mode" "INFO" "planning only; no files are copied"
  status_line "Site" "INFO" "$(docker_site_name)"
  status_line "Host artifact source" "INFO" "$(docker_offvm_source_dir)/"
  status_line "Target" "$([[ -n "${OFF_VM_BACKUP_TARGET:-}" ]] && echo INFO || echo WARN)" "$(off_vm_backup_target_display)"
  status_line "Transport" "INFO" "rsync over SSH (destination checksum-verified)"
  status_line "Delete mode" "INFO" "${OFF_VM_BACKUP_RSYNC_DELETE:-false}"
  echo
  echo "Chain: container backup -> durable host artifact -> off-VM -> object storage."
  echo "  1) Take a durable host backup:      $(toolkit_cmd backup-files)"
  echo "  2) Configure the rsync target:      $(toolkit_cmd configure-rsync-backup-target)"
  echo "  3) Dry run, then real off-VM copy:  $(toolkit_cmd off-vm-backup-dry-run) / $(toolkit_cmd run-off-vm-backup)"
  echo "  4) Also push to object storage:     $(toolkit_cmd docker-object-config) then $(toolkit_cmd docker-object-backup)"
  ui_next "$(toolkit_cmd configure-rsync-backup-target)" "$(toolkit_cmd off-vm-backup-dry-run)" "$(toolkit_cmd docker-object-config)"
  ui_box_end
}

docker_offvm_status() {
  require_sudo
  local target_status target_detail last_status last_run last_detail src set_count
  off_vm_backup_load_config
  if off_vm_backup_configured; then
    target_status="OK"; target_detail="$OFF_VM_BACKUP_TARGET"
  else
    target_status="WARN"; target_detail="not configured"
  fi
  last_status="$(off_vm_backup_last_state LAST_STATUS 2>/dev/null || echo none)"
  last_run="$(off_vm_backup_last_state LAST_RUN_AT 2>/dev/null || echo never)"
  last_detail="$(off_vm_backup_last_state LAST_DETAIL 2>/dev/null || echo "no previous run")"
  src="$(docker_offvm_source_dir)"
  set_count=0
  if $SUDO test -d "$src"; then
    set_count="$($SUDO find "$src" -maxdepth 1 -mindepth 1 -type d 2>/dev/null | wc -l | awk '{print $1+0}')"
  fi

  ui_box_start "Docker Off-VM Backup Status"
  status_line "Engine" "INFO" "Docker ($(docker_mode_label))"
  status_line "Host artifact sets" "$([[ "$set_count" -gt 0 ]] && echo OK || echo WARN)" "${set_count} set(s) in ${src}"
  status_line "Target" "$target_status" "$target_detail"
  status_line "Config file" "$($SUDO test -f "$OFF_VM_BACKUP_CONFIG_FILE" && echo OK || echo WARN)" "$OFF_VM_BACKUP_CONFIG_FILE"
  case "$last_status" in
    OK) status_line "Last off-VM run" "OK" "${last_run}; ${last_detail}" ;;
    FAIL) status_line "Last off-VM run" "FAIL" "${last_run}; ${last_detail}" ;;
    *) status_line "Last off-VM run" "INFO" "${last_run}; ${last_detail}" ;;
  esac
  echo
  docker_object_backup_status_line
  echo
  echo "Off-site backup protects against VM/disk loss only when the destination is"
  echo "outside this VM and, ideally, this cloud account."
  ui_next "$(toolkit_cmd off-vm-backup-dry-run)" "$(toolkit_cmd run-off-vm-backup)" "$(toolkit_cmd docker-object-backup)"
  ui_box_end
}

# ---- Object storage (rclone) --------------------------------------------------
docker_object_backup_load_config() {
  local v
  if [[ -z "${DOCKER_OBJECT_RCLONE_REMOTE:-}" ]]; then
    v="$(docker_env_value "$DOCKER_OBJECT_BACKUP_CONFIG_FILE" DOCKER_OBJECT_RCLONE_REMOTE)"; [[ -n "$v" ]] && DOCKER_OBJECT_RCLONE_REMOTE="$v"
  fi
  if [[ -z "${DOCKER_OBJECT_BUCKET:-}" ]]; then
    v="$(docker_env_value "$DOCKER_OBJECT_BACKUP_CONFIG_FILE" DOCKER_OBJECT_BUCKET)"; [[ -n "$v" ]] && DOCKER_OBJECT_BUCKET="$v"
  fi
  if [[ -z "${DOCKER_OBJECT_PREFIX:-}" ]]; then
    v="$(docker_env_value "$DOCKER_OBJECT_BACKUP_CONFIG_FILE" DOCKER_OBJECT_PREFIX)"; [[ -n "$v" ]] && DOCKER_OBJECT_PREFIX="$v"
  fi
}

docker_object_backup_configured() {
  docker_object_backup_load_config
  [[ -n "${DOCKER_OBJECT_RCLONE_REMOTE:-}" && -n "${DOCKER_OBJECT_BUCKET:-}" ]]
}

# Full rclone destination: <remote>:<bucket>/<prefix>/<site>.
docker_object_dest() {
  docker_object_backup_load_config
  local prefix="${DOCKER_OBJECT_PREFIX:-}"
  prefix="${prefix#/}"; prefix="${prefix%/}"
  if [[ -n "$prefix" ]]; then
    printf '%s:%s/%s/%s\n' "$DOCKER_OBJECT_RCLONE_REMOTE" "$DOCKER_OBJECT_BUCKET" "$prefix" "$(docker_site_name)"
  else
    printf '%s:%s/%s\n' "$DOCKER_OBJECT_RCLONE_REMOTE" "$DOCKER_OBJECT_BUCKET" "$(docker_site_name)"
  fi
}

docker_object_ensure_rclone() {
  command -v rclone >/dev/null 2>&1 && return 0
  log "Installing rclone"
  export DEBIAN_FRONTEND=noninteractive
  $SUDO apt-get update -y >/dev/null 2>&1 || true
  $SUDO apt-get install -y rclone >/dev/null 2>&1 || return 1
  command -v rclone >/dev/null 2>&1
}

docker_object_backup_write_state() {
  require_sudo
  local status="$1" detail="$2" now
  now="$(date -Is 2>/dev/null || date)"
  $SUDO mkdir -p "$(dirname "$DOCKER_OBJECT_BACKUP_STATE_FILE")"
  $SUDO tee "$DOCKER_OBJECT_BACKUP_STATE_FILE" >/dev/null <<EOF_DOCKER_OBJ_STATE
LAST_RUN_AT=${now}
LAST_STATUS=${status}
LAST_DETAIL=${detail}
LAST_DEST=$(docker_object_dest 2>/dev/null || echo unknown)
SITE_NAME=$(docker_site_name)
EOF_DOCKER_OBJ_STATE
  $SUDO chown root:root "$DOCKER_OBJECT_BACKUP_STATE_FILE" 2>/dev/null || true
  $SUDO chmod 600 "$DOCKER_OBJECT_BACKUP_STATE_FILE" 2>/dev/null || true
}

# One-line object-storage summary used inside docker_offvm_status.
docker_object_backup_status_line() {
  local last_status last_run
  if docker_object_backup_configured; then
    last_status="$(docker_env_value "$DOCKER_OBJECT_BACKUP_STATE_FILE" LAST_STATUS)"
    last_run="$(docker_env_value "$DOCKER_OBJECT_BACKUP_STATE_FILE" LAST_RUN_AT)"
    case "${last_status:-none}" in
      OK) status_line "Object storage" "OK" "$(docker_object_dest); last OK ${last_run:-?}" ;;
      FAIL) status_line "Object storage" "WARN" "$(docker_object_dest); last run FAILED ${last_run:-?}" ;;
      *) status_line "Object storage" "INFO" "$(docker_object_dest); no successful run yet" ;;
    esac
  else
    status_line "Object storage" "WARN" "not configured; run $(toolkit_cmd docker-object-config)"
  fi
}

configure_docker_object_backup() {
  require_sudo
  local remote bucket prefix
  docker_object_backup_load_config

  if ! docker_object_ensure_rclone; then
    fail "rclone is required for object-storage backups but could not be installed. Install rclone, then retry."
  fi

  ui_box_start "Configure Object-Storage Backup (rclone)"
  status_line "Site" "INFO" "$(docker_site_name)"
  status_line "Tool" "INFO" "rclone $(rclone version 2>/dev/null | awk 'NR==1{print $2}')"
  echo
  echo "Uses an existing rclone remote. Create one first with:  rclone config"
  echo "(supports S3, Cloudflare R2, Backblaze B2, GCS, Azure, MinIO, and more)."
  echo
  echo "Configured rclone remotes:"
  rclone listremotes 2>/dev/null | sed 's/^/  /' || echo "  (none — run 'rclone config' first)"
  echo

  if [[ -t 0 && "${ASSUME_YES:-0}" -ne 1 ]]; then
    read -r -p "rclone remote name (e.g. r2): " remote
    remote="${remote%:}"
    read -r -p "Bucket / container name: " bucket
    read -r -p "Path prefix inside the bucket [erpnext-backups]: " prefix
    prefix="${prefix:-erpnext-backups}"
  else
    remote="${DOCKER_OBJECT_RCLONE_REMOTE:-}"
    bucket="${DOCKER_OBJECT_BUCKET:-}"
    prefix="${DOCKER_OBJECT_PREFIX:-erpnext-backups}"
    [[ -n "$remote" && -n "$bucket" ]] || fail "Set DOCKER_OBJECT_RCLONE_REMOTE and DOCKER_OBJECT_BUCKET before using --yes."
  fi

  [[ -n "$remote" && -n "$bucket" ]] || fail "Remote name and bucket are required."
  if ! rclone listremotes 2>/dev/null | grep -qx "${remote}:"; then
    warn "rclone remote '${remote}:' is not in 'rclone listremotes'. Save anyway; create it with 'rclone config'."
  fi

  $SUDO mkdir -p "$(dirname "$DOCKER_OBJECT_BACKUP_CONFIG_FILE")"
  $SUDO tee "$DOCKER_OBJECT_BACKUP_CONFIG_FILE" >/dev/null <<EOF_DOCKER_OBJ_CONFIG
# ERPNext Developer Toolkit - Docker object-storage backup (rclone) configuration
# Non-secret only. rclone credentials live in the rclone config (rclone config).
DOCKER_OBJECT_RCLONE_REMOTE=${remote}
DOCKER_OBJECT_BUCKET=${bucket}
DOCKER_OBJECT_PREFIX=${prefix}
SITE_NAME=$(docker_site_name)
EOF_DOCKER_OBJ_CONFIG
  $SUDO chown root:root "$DOCKER_OBJECT_BACKUP_CONFIG_FILE" 2>/dev/null || true
  $SUDO chmod 600 "$DOCKER_OBJECT_BACKUP_CONFIG_FILE" 2>/dev/null || true
  DOCKER_OBJECT_RCLONE_REMOTE="$remote"
  DOCKER_OBJECT_BUCKET="$bucket"
  DOCKER_OBJECT_PREFIX="$prefix"

  ui_box_start "Object-Storage Backup Configured"
  status_line "Destination" "OK" "$(docker_object_dest)"
  status_line "Config file" "OK" "$DOCKER_OBJECT_BACKUP_CONFIG_FILE"
  ui_next "$(toolkit_cmd docker-object-backup-dry-run)" "$(toolkit_cmd docker-object-backup)"
  ui_box_end
}

# Upload durable host artifacts to object storage with rclone. mode: dry-run|run.
# Uploads are checksum-based (rclone --checksum) and verified with rclone check.
run_docker_object_backup() {
  require_sudo
  local mode="${1:-run}" src dest
  local -a rclone_cmd=()

  docker_object_backup_load_config
  docker_object_backup_configured || fail "Object storage not configured. Run: $(toolkit_cmd docker-object-config)"
  docker_object_ensure_rclone || fail "rclone is not available. Install rclone, then retry."
  src="$(docker_offvm_source_dir)"
  $SUDO test -d "$src" || fail "No durable host backups at ${src}. Run $(toolkit_cmd backup) first."
  dest="$(docker_object_dest)"

  ui_box_start "$([[ "$mode" == "dry-run" ]] && echo "Object-Storage Backup Dry Run" || echo "Object-Storage Backup")"
  status_line "Site" "INFO" "$(docker_site_name)"
  status_line "Source" "INFO" "${src}/ (durable host artifacts)"
  status_line "Destination" "INFO" "$dest"
  echo

  rclone_cmd=(rclone copy "$src" "$dest" --checksum --transfers 4 --stats-one-line)
  [[ "$mode" == "dry-run" ]] && rclone_cmd+=(--dry-run)

  if [[ "$mode" != "dry-run" && -t 0 && "${ASSUME_YES:-0}" -ne 1 ]]; then
    if ! confirm "Upload durable host backups to ${dest} now?"; then
      warn "Object-storage backup cancelled."
      ui_box_end
      return 0
    fi
  fi

  log "Starting rclone ${mode}"
  if ${SUDO:-} "${rclone_cmd[@]}"; then
    if [[ "$mode" == "dry-run" ]]; then
      status_line "Dry run" "OK" "rclone dry run completed"
    elif ${SUDO:-} rclone check "$src" "$dest" --one-way --checksum >/dev/null 2>&1; then
      status_line "Remote verify" "OK" "rclone check confirmed all files present"
      docker_object_backup_write_state "OK" "rclone copy + check verified"
      status_line "Object storage" "OK" "uploaded and verified"
    else
      status_line "Remote verify" "WARN" "rclone check reported differences"
      docker_object_backup_write_state "OK" "rclone copy completed; check reported differences"
      status_line "Object storage" "WARN" "uploaded (verify manually with rclone check)"
    fi
  else
    [[ "$mode" != "dry-run" ]] && docker_object_backup_write_state "FAIL" "rclone copy failed"
    status_line "Object storage" "FAIL" "rclone command failed"
  fi
  ui_next "$(toolkit_cmd docker-object-status)" "$(toolkit_cmd off-vm-backup-status)"
  ui_box_end
}

show_docker_object_backup_status() {
  require_sudo
  docker_object_backup_load_config
  ui_box_start "Object-Storage Backup Status"
  status_line "Site" "INFO" "$(docker_site_name)"
  status_line "rclone" "$(command -v rclone >/dev/null 2>&1 && echo OK || echo WARN)" "$(command -v rclone >/dev/null 2>&1 && rclone version 2>/dev/null | awk 'NR==1{print $2}' || echo 'not installed')"
  status_line "Config file" "$($SUDO test -f "$DOCKER_OBJECT_BACKUP_CONFIG_FILE" && echo OK || echo WARN)" "$DOCKER_OBJECT_BACKUP_CONFIG_FILE"
  if docker_object_backup_configured; then
    status_line "Destination" "OK" "$(docker_object_dest)"
  else
    status_line "Destination" "WARN" "not configured"
  fi
  docker_object_backup_status_line
  ui_next "$(toolkit_cmd docker-object-backup-dry-run)" "$(toolkit_cmd docker-object-backup)"
  ui_box_end
}

# Install an app inside the running container. Container app installs are not
# persisted across image upgrades (the recommended path is a custom image); we
# warn accordingly. args: app_name display repo branch notes
docker_install_app() {
  require_sudo
  local app_name="$1" display="$2" repo="$3" branch="$4"
  local site
  site="$(docker_site_name)"

  warn "Docker engine: apps are installed into the running container."
  warn "This is ideal for evaluation. For durable deployments, build a custom image (planned: docker-custom-image)."

  if ! confirm "Install ${display} into the ERPNext container now?"; then
    warn "App installation cancelled."
    return 0
  fi

  if [[ -n "$branch" ]]; then
    docker_bench get-app "$repo" --branch "$branch" || fail "Could not fetch ${display} in the container."
  else
    docker_bench get-app "$repo" || fail "Could not fetch ${display} in the container."
  fi
  docker_bench --site "$site" install-app "$app_name" || fail "Could not install ${display} on ${site}."
  docker_bench --site "$site" migrate || warn "migrate reported an issue."
  docker_runtime_restart || true
  ok "${display} installed into the ERPNext container."
}

docker_print_access() {
  local site vm_ip
  site="$(docker_site_name)"
  vm_ip="$(get_vm_ip 2>/dev/null || echo unknown)"
  ui_box_start "ERPNext (Docker) Access"
  status_line "Site" "OK" "$site"
  status_line "Local URL" "INFO" "http://localhost:${DOCKER_PUBLISH_PORT}"
  if [[ "$vm_ip" != "unknown" && -n "$vm_ip" ]]; then
    status_line "Network URL" "INFO" "http://${vm_ip}:${DOCKER_PUBLISH_PORT}"
  fi
  status_line "Friendly URL" "INFO" "http://${site}:${DOCKER_PUBLISH_PORT}"
  status_line "Login" "INFO" "Administrator"
  status_line "Credentials" "INFO" "$DOCKER_CREDENTIALS_FILE"
  status_line "Compose project" "INFO" "$DOCKER_PROJECT_NAME"
  ui_box_end
  echo "Local URL works on this machine. Network URL works from your host / LAN."
  echo "The Friendly URL (${site}) works only after your HOST maps it to this machine:"
  print_host_dns_commands_for_site "$site" "$vm_ip"
  echo "Then open: http://${site}:${DOCKER_PUBLISH_PORT}"
}

# Single programmatic URL (doctor / engine_site_url). Prefer the network IP so
# it is reachable from the host; fall back to loopback when the IP is unknown.
docker_site_url() {
  local vm_ip
  vm_ip="$(get_vm_ip 2>/dev/null || echo unknown)"
  if [[ "$vm_ip" != "unknown" && -n "$vm_ip" ]]; then
    printf 'http://%s:%s\n' "$vm_ip" "$DOCKER_PUBLISH_PORT"
  else
    printf 'http://localhost:%s\n' "$DOCKER_PUBLISH_PORT"
  fi
}

# Docker-specific host-mapping checkpoint. Reuses the accurate, port-agnostic
# host DNS command generator (maps the domain to this machine's IP) but prints
# guidance for the Docker published port rather than the native 8000.
docker_host_mapping_checkpoint() {
  require_sudo
  local site vm_ip
  site="$(docker_site_name)"
  vm_ip="$(get_vm_ip 2>/dev/null || echo unknown)"
  echo
  echo "============================================================"
  echo "Host Mapping Checkpoint (friendly domain)"
  echo "============================================================"
  echo
  echo "To open ERPNext as ${site} in a browser, your HOST machine must map the"
  echo "domain to this machine. The Docker stack serves HTTP on port ${DOCKER_PUBLISH_PORT}."
  echo
  status_line "Local domain" "INFO" "$site"
  status_line "Detected host IP" "$([[ "$vm_ip" != unknown ]] && echo OK || echo WARN)" "$vm_ip"
  status_line "Host OS" "INFO" "$(host_os_label)"
  if host_os_is_unset; then
    echo
    echo "Host OS not chosen yet; showing $(host_os_label) commands by default."
    echo "If your host is macOS or Windows, run: $(toolkit_cmd set-host-os)"
  fi
  echo
  echo "Run this on your $(host_os_label) HOST machine (not inside the VM)."
  echo "It is safe to repeat; it backs up the hosts file and refreshes the mapping:"
  print_host_dns_commands_for_site "$site" "$vm_ip"
  echo
  echo "Then open: http://${site}:${DOCKER_PUBLISH_PORT}"
  echo "============================================================"
}

# Docker engine access verification (parity with native verify_access).
docker_verify_access() {
  require_sudo
  local site code url
  site="$(docker_site_name)"
  url="http://localhost:${DOCKER_PUBLISH_PORT}/api/method/ping"

  echo
  echo "============================================================"
  echo "Access Verification (Docker)"
  echo "============================================================"

  if docker_compose ps 2>/dev/null | grep -qiE 'running|up'; then
    status_line "Containers" "OK" "compose services running"
  else
    status_line "Containers" "WARN" "no running services (try: $(toolkit_cmd start))"
  fi

  # Send the site Host header so Frappe resolves the target site.
  code="$(curl -s -o /dev/null -w '%{http_code}' --max-time 8 -H "Host: ${site}" "$url" 2>/dev/null || true)"
  case "$code" in
    200|401|403) status_line "Published port" "OK" "http://localhost:${DOCKER_PUBLISH_PORT} (HTTP ${code})" ;;
    "") status_line "Published port" "WARN" "no response on http://localhost:${DOCKER_PUBLISH_PORT}" ;;
    *) status_line "Published port" "WARN" "HTTP ${code} on http://localhost:${DOCKER_PUBLISH_PORT}" ;;
  esac

  docker_print_access
}

# Docker engine "what now" summary printed at the end of the guided install.
docker_show_next_steps() {
  echo
  echo "============================================================"
  echo "Docker Engine - Next Steps"
  echo "============================================================"
  echo "  Open ERPNext:        http://localhost:${DOCKER_PUBLISH_PORT}  (Administrator)"
  echo "  Friendly domain:     see the host mapping checkpoint above"
  echo "  Verify access:       $(toolkit_cmd verify-access)"
  echo "  Start / stop:        $(toolkit_cmd start) / $(toolkit_cmd stop)"
  echo "  Status / logs:       $(toolkit_cmd status) / $(toolkit_cmd logs)"
  echo "  Backups:             $(toolkit_cmd backup) / $(toolkit_cmd list-backups)"
  echo "  Optional apps:       $(toolkit_cmd app-install-wizard)"
  echo "  Engine status:       $(toolkit_cmd engine-status)"
  echo
  echo "Trusted local HTTPS for the Docker engine is planned for the reverse-proxy"
  echo "phase (v1.11.0). For now the stack serves over HTTP on the published port."
  echo "============================================================"
}

# Compact, Docker-safe app installer. The native run_app_install_wizard requires
# a host bench dir (require_site_environment), which does not exist for the
# Docker engine; install_app_profile -> install_frappe_app routes to
# docker_install_app (the container path) so we drive that directly here.
docker_app_install_wizard() {
  require_sudo
  local choice
  while true; do
    echo
    echo "============================================================"
    echo "Docker App Installation"
    echo "============================================================"
    echo "Apps install into the running container (ideal for evaluation)."
    echo "For durable deployments, build a custom image (planned: docker-custom-image)."
    echo
    echo "  1) CRM               6) Webshop / E-Commerce"
    echo "  2) HR / HRMS         7) Builder"
    echo "  3) Helpdesk          8) Insights"
    echo "  4) Payments          9) Print Designer"
    echo "  5) Learning / LMS   10) Wiki"
    echo "  b) Back"
    echo "============================================================"
    read -r -p "Choose an app to install [b]: " choice
    case "$choice" in
      1) install_app_profile crm ;;
      2) install_app_profile hrms ;;
      3) install_app_profile helpdesk ;;
      4) install_app_profile payments ;;
      5) install_app_profile lms ;;
      6) install_app_profile webshop ;;
      7) install_app_profile builder ;;
      8) install_app_profile insights ;;
      9) install_app_profile print_designer ;;
      10) install_app_profile wiki ;;
      b|B|"") return 0 ;;
      q|Q) exit 0 ;;
      *) warn "Invalid option" ;;
    esac
  done
}

docker_prompt_open_main_menu() {
  local reply
  [[ -t 0 ]] || return 0
  echo
  read -r -p "Open the main toolkit menu now? [Y/n]: " reply
  reply="${reply:-Y}"
  if [[ "$reply" =~ ^[Yy]$ ]]; then
    show_menu
  else
    echo "Open it later with: $(toolkit_cmd menu)"
  fi
}

# Post-install continuation for the Docker engine, mirroring the native
# run_guided_setup tail but engine-appropriate. Interactive steps are skipped
# under -y / non-TTY (matching native local_guided_followups) so automation and
# CI stay non-interactive.
docker_guided_followups() {
  docker_verify_access
  docker_host_mapping_checkpoint

  if [[ -t 0 && "${ASSUME_YES:-0}" -ne 1 ]]; then
    if confirm "Install optional Frappe apps now?"; then
      docker_app_install_wizard
    fi
    if confirm "Take an initial database backup now?"; then
      docker_backup false || warn "Backup did not complete."
    fi
  fi

  docker_show_next_steps
  docker_prompt_open_main_menu
}

# doctor rows for the Docker engine.
docker_doctor_detail() {
  local compat
  if docker_daemon_ready; then
    compat="daemon OK"
  elif docker_binary_present; then
    compat="installed, daemon down"
  else
    compat="not installed"
  fi
  doctor_add_check "Docker" "$([[ "$compat" == "daemon OK" ]] && echo OK || echo WARN)" "$compat"
  if [[ -f "$(docker_compose_base_file)" ]]; then
    doctor_add_check "Compose stack" "OK" "$(docker_clone_dir)"
  else
    doctor_add_check "Compose stack" "WARN" "not provisioned"
  fi
}

# ------------------------------------------------------------
# Production provisioning (compose.yaml + upstream overrides)
# ------------------------------------------------------------
# Generate the production env file consumed by compose interpolation. Uses a
# generated random DB root password (unlike the dev default) and forces the
# frontend to resolve the single configured site by host header.
docker_write_prod_env() {
  require_sudo
  local envf site admin_pw db_pw tag
  envf="$(docker_prod_env_file)"
  site="$(docker_site_name)"
  admin_pw="${DOCKER_ADMIN_PASSWORD:-$(random_password)}"
  db_pw="${DOCKER_DB_ROOT_PASSWORD:-$(random_password)}"
  DOCKER_ADMIN_PASSWORD="$admin_pw"
  DOCKER_DB_ROOT_PASSWORD="$db_pw"
  tag="$(docker_image_tag)"

  $SUDO mkdir -p "$DOCKER_WORKDIR"
  $SUDO tee "$envf" >/dev/null <<EOF_DOCKER_PROD_ENV
# ERPNext Developer Toolkit - Docker production env (compose.yaml interpolation)
ERPNEXT_VERSION=${tag}
DB_PASSWORD=${db_pw}
HTTP_PUBLISH_PORT=${DOCKER_PUBLISH_PORT}
FRAPPE_SITE_NAME_HEADER=${site}
EOF_DOCKER_PROD_ENV
  $SUDO chown root:root "$envf" 2>/dev/null || true
  $SUDO chmod 600 "$envf" 2>/dev/null || true

  $SUDO tee "$DOCKER_CREDENTIALS_FILE" >/dev/null <<EOF_DOCKER_PROD_CREDS
# ERPNext Developer Toolkit - Docker engine credentials (production)
# Site:      ${site}
# Local URL: http://localhost:${DOCKER_PUBLISH_PORT}
# Friendly:  http://${site}:${DOCKER_PUBLISH_PORT} (after host/DNS mapping)
Administrator password: ${admin_pw}
MariaDB root password:  ${db_pw}
EOF_DOCKER_PROD_CREDS
  $SUDO chown root:root "$DOCKER_CREDENTIALS_FILE" 2>/dev/null || true
  $SUDO chmod 600 "$DOCKER_CREDENTIALS_FILE" 2>/dev/null || true
}

# Generated override that pins the ERPNext image across every customizable
# service in compose.yaml. Setting image: directly supports both tag and digest
# pins (the upstream CUSTOM_IMAGE/CUSTOM_TAG split cannot express a digest).
docker_write_prod_image_override() {
  require_sudo
  local f svc
  f="$(docker_prod_image_override_file)"
  $SUDO mkdir -p "$DOCKER_WORKDIR"
  {
    echo "services:"
    for svc in configurator backend frontend websocket queue-short queue-long scheduler; do
      echo "  ${svc}:"
      echo "    image: ${DOCKER_ERPNEXT_IMAGE}"
    done
  } | $SUDO tee "$f" >/dev/null
  $SUDO chown root:root "$f" 2>/dev/null || true
  $SUDO chmod 644 "$f" 2>/dev/null || true
}

# Wait for a named compose service container to reach "running".
docker_wait_service_running() {
  local svc="${1:-backend}" timeout="${2:-300}" deadline cid state
  deadline=$(( $(date +%s) + timeout ))
  while :; do
    cid="$(docker_compose ps -q "$svc" 2>/dev/null | tail -n1)"
    if [[ -n "$cid" ]]; then
      state="$(${SUDO:-} docker inspect -f '{{.State.Status}}' "$cid" 2>/dev/null || echo unknown)"
      [[ "$state" == "running" ]] && return 0
    fi
    [[ "$(date +%s)" -ge "$deadline" ]] && return 1
    sleep 5
  done
}

# Create the site in production by exec'ing bench new-site into the backend.
# compose.yaml has no create-site container, so we wait for the configurator
# one-shot to complete (it writes common_site_config), then run new-site once.
docker_prod_create_site() {
  require_sudo
  local site deadline now cid state code
  site="$(docker_site_name)"

  log "Waiting for the configurator job to complete before creating ${site}"
  deadline=$(( $(date +%s) + DOCKER_CREATE_SITE_TIMEOUT ))
  while :; do
    cid="$(docker_compose ps -aq configurator 2>/dev/null | tail -n1)"
    if [[ -n "$cid" ]]; then
      state="$(${SUDO:-} docker inspect -f '{{.State.Status}}' "$cid" 2>/dev/null || echo unknown)"
      if [[ "$state" == "exited" ]]; then
        code="$(${SUDO:-} docker inspect -f '{{.State.ExitCode}}' "$cid" 2>/dev/null || echo 1)"
        if [[ "$code" == "0" ]]; then
          break
        fi
        err "configurator job failed (exit ${code}). Recent logs:"
        docker_compose logs --no-color --tail 120 configurator 2>/dev/null || true
        return 1
      fi
    fi
    now="$(date +%s)"
    if [[ "$now" -ge "$deadline" ]]; then
      warn "configurator did not complete within ${DOCKER_CREATE_SITE_TIMEOUT}s. Recent logs:"
      docker_compose logs --no-color --tail 120 configurator 2>/dev/null || true
      return 1
    fi
    sleep 5
  done

  docker_wait_service_running backend 300 || { err "backend container did not reach running state."; return 1; }

  if docker_compose exec -T backend test -f "sites/${site}/site_config.json" >/dev/null 2>&1; then
    ok "Site ${site} already exists; skipping create-site."
    return 0
  fi

  log "Creating site ${site} (bench new-site inside the backend container)"
  if ! docker_compose exec -T backend bench new-site \
      --mariadb-user-host-login-scope='%' \
      --admin-password "$DOCKER_ADMIN_PASSWORD" \
      --db-root-username root \
      --db-root-password "$DOCKER_DB_ROOT_PASSWORD" \
      --install-app erpnext \
      --set-default "$site"; then
    err "bench new-site failed for ${site}. Inspect with: $(toolkit_cmd logs)"
    return 1
  fi
  ok "Site created: ${site}"
}

# Entry point for the docker-production-setup command: force the Docker engine
# in production mode, then run the guided install.
run_docker_production_setup() {
  require_sudo
  # These globals are consumed cross-file (effective_deployment_engine and the
  # config loader in lib/config.sh); shellcheck cannot see that use here.
  # shellcheck disable=SC2034
  DEPLOYMENT_ENGINE="docker"
  # shellcheck disable=SC2034
  DEPLOYMENT_ENGINE_ENV_PROVIDED=1
  DOCKER_MODE="production"
  # shellcheck disable=SC2034
  DOCKER_MODE_ENV_PROVIDED=1
  echo "Deployment engine: Docker (production mode)"
  docker_guided_install
}

# Production guided install: wraps compose.yaml + upstream overrides.
docker_prod_guided_install() {
  require_sudo
  install_self_for_reuse || fail "Could not install the toolkit to ${INSTALLER_CANONICAL_PATH:-/opt/erpnext-dev/erpnext-dev.sh}"

  docker_ensure_publish_port
  docker_preflight

  if [[ -t 0 && "${ASSUME_YES:-0}" -ne 1 ]]; then
    if ! confirm "Provision the PRODUCTION Docker ERPNext stack now?"; then
      echo "Next command:"
      echo "  $(toolkit_cmd install)"
      return 0
    fi
  fi

  docker_install_engine
  docker_provision_workdir
  docker_write_prod_env
  docker_write_prod_image_override

  # Persist engine + mode so lifecycle commands route to the production stack.
  # shellcheck disable=SC2034  # consumed by write_dev_config_file in lib/config.sh
  DEPLOYMENT_ENGINE="docker"
  DOCKER_MODE="production"
  SITE_NAME="$(docker_site_name)"
  write_dev_config_file

  docker_compose_up || fail "docker compose up failed. Inspect with: $(toolkit_cmd logs)"
  docker_prod_create_site || fail "Site creation failed. See the logs above, or run: $(toolkit_cmd logs)"
  docker_ready || warn "Stack started but readiness check timed out; it may still be initializing."
  docker_write_pins || warn "Could not record immutable pins."
  ok "Docker production stack setup complete."
  echo
  echo "NOTE: This stack currently serves over HTTP on the published port."
  echo "Trusted production HTTPS (Traefik + Let's Encrypt) arrives in the next phase (P5)."
  docker_guided_followups
}

# ------------------------------------------------------------
# Guided install (Docker engine entry point)
# ------------------------------------------------------------
docker_guided_install() {
  # Production mode wraps compose.yaml; development keeps the disposable pwd.yml
  # flow below (the one-keystroke default).
  if docker_is_production; then
    docker_prod_guided_install
    return
  fi

  require_sudo
  install_self_for_reuse || fail "Could not install the toolkit to ${INSTALLER_CANONICAL_PATH:-/opt/erpnext-dev/erpnext-dev.sh}"

  # Resolve any published-port conflict before the preflight so the summary and
  # all downstream output reflect the port we will actually publish.
  docker_ensure_publish_port

  docker_preflight

  if [[ -t 0 && "${ASSUME_YES:-0}" -ne 1 ]]; then
    if ! confirm "Provision the Docker ERPNext stack now?"; then
      echo "Next command:"
      echo "  $(toolkit_cmd install)"
      return 0
    fi
  fi

  docker_install_engine
  docker_provision_workdir
  docker_write_env
  docker_write_override

  # Persist engine selection + docker settings so lifecycle commands route here.
  # shellcheck disable=SC2034  # consumed by write_dev_config_file in lib/config.sh
  DEPLOYMENT_ENGINE="docker"
  # shellcheck disable=SC2034  # consumed by write_dev_config_file in lib/config.sh
  DEPLOYMENT_MODE="development"
  SITE_NAME="$(docker_site_name)"
  write_dev_config_file

  docker_compose_up || fail "docker compose up failed. Inspect with: $(toolkit_cmd logs)"
  docker_wait_for_site_creation || fail "Site creation failed. See the create-site logs above, or run: $(toolkit_cmd logs)"
  docker_ready || warn "Stack started but readiness check timed out; it may still be initializing."
  docker_write_pins || warn "Could not record immutable pins."
  ok "Docker deployment engine setup complete."
  docker_guided_followups
}
